// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqiphooudzhkzdoybwag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxaXBob291ZHpoa3pkb3lid2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MzcwMTYsImV4cCI6MjA2MDAxMzAxNn0.n9f9s7o8BSpHev5l-LQTFo-4YpZqvJ_dWaVv4dR538I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});